// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_f0b820c4d93e7a247ae2b37d3a1d9b32_a45c1efe_69b1_4a6b_93a2_378fa1ccf742 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}


	[Preserve]
	public class CoherenceSyncCoin_f0b820c4d93e7a247ae2b37d3a1d9b32 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncCoin_f0b820c4d93e7a247ae2b37d3a1d9b32>();

		// Cached targets for commands		
		private global::Coin Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["a45c1efe-69b1-4a6b-93a2-378fa1ccf742"] = new Binding_f0b820c4d93e7a247ae2b37d3a1d9b32_a45c1efe_69b1_4a6b_93a2_378fa1ccf742(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncCoin_f0b820c4d93e7a247ae2b37d3a1d9b32()
		{
			bakedCommandBindings.Add("113a2d09-0ad2-4bec-92ba-44995a582c44", BakeCommandBinding_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44_CommandTarget = (global::Coin)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("Coin.RequestDestroy", "()",
				SendCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44, ReceiveLocalCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44, MessageTarget.AuthorityOnly, Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncCoin_f0b820c4d93e7a247ae2b37d3a1d9b32>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(MessageTarget target, object[] args)
		{
			var command = new Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(MessageTarget target, object[] args)
		{
			var command = new Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44();
			ReceiveCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(command);
		}

		void ReceiveCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44 command)
		{
			var target = Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44_CommandTarget;
			target.RequestDestroy();
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44 castedCommand:
					ReceiveCommand_Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncCoin_f0b820c4d93e7a247ae2b37d3a1d9b32] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
