// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_3493eddc_ba56_4f3d_88f2_c12377d7992d : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_715604fc_52a2_4f26_90ca_248221e0337a : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_7b0f513a_75e2_4c53_85e7_37449ac04450 : IntBinding
	{
		private global::CoinCollector CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::CoinCollector)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_acaa15b2fd77b2a4080fa3b9f1088f0e_CoinCollector_3534918425276488611";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.collected);
			set => CastedUnityComponent.collected = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_acaa15b2fd77b2a4080fa3b9f1088f0e_CoinCollector_3534918425276488611)coherenceComponent).collected;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player_acaa15b2fd77b2a4080fa3b9f1088f0e_CoinCollector_3534918425276488611)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.collected = Value;
			}
			else 
			{
				update.collected = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_CoinCollector_3534918425276488611();
		}
	}

	public class Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_c53e0da3_8377_4e14_adfd_3a8755bdbde6 : IntBinding
	{
		private global::Player CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::Player)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player_2827779321465607972";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.Health);
			set => CastedUnityComponent.Health = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player_2827779321465607972)coherenceComponent).Health;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player_2827779321465607972)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.Health = Value;
			}
			else 
			{
				update.Health = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player_2827779321465607972();
		}
	}

	public class Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_ce65511c_04bc_43d2_b04e_bd1f7ae79ca3 : ColorBinding
	{
		private global::UnityEngine.SpriteRenderer CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.color);
			set => CastedUnityComponent.color = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973)coherenceComponent).color;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.color = Value;
			}
			else 
			{
				update.color = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973();
		}
	}


	[Preserve]
	public class CoherenceSyncPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e>();

		// Cached targets for commands		
		private global::ColorRequester Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e_CommandTarget;		
		private global::Player Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04_CommandTarget;		
		private global::PlayerInput Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["3493eddc-ba56-4f3d-88f2-c12377d7992d"] = new Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_3493eddc_ba56_4f3d_88f2_c12377d7992d(),
			["715604fc-52a2-4f26-90ca-248221e0337a"] = new Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_715604fc_52a2_4f26_90ca_248221e0337a(),
			["7b0f513a-75e2-4c53-85e7-37449ac04450"] = new Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_7b0f513a_75e2_4c53_85e7_37449ac04450(),
			["c53e0da3-8377-4e14-adfd-3a8755bdbde6"] = new Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_c53e0da3_8377_4e14_adfd_3a8755bdbde6(),
			["ce65511c-04bc-43d2-b04e-bd1f7ae79ca3"] = new Binding_acaa15b2fd77b2a4080fa3b9f1088f0e_ce65511c_04bc_43d2_b04e_bd1f7ae79ca3(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e()
		{
			bakedCommandBindings.Add("66a6aa74-9d10-4e8c-b171-36b364efe44e", BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e);
			bakedCommandBindings.Add("c2c9cd5c-69d7-4f17-9c6b-c032639a3e04", BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04);
			bakedCommandBindings.Add("1037d901-6009-4a9c-a441-b730289e3050", BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e_CommandTarget = (global::ColorRequester)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("ColorRequester.GotColor", "(UnityEngine.Color)",
				SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e, ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e, MessageTarget.AuthorityOnly, Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e_CommandTarget,false);
		}
		private void BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04_CommandTarget = (global::Player)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("Player.Hit", "()",
				SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04, ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04, MessageTarget.AuthorityOnly, Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04_CommandTarget,false);
		}
		private void BakeCommandBinding_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050_CommandTarget = (global::PlayerInput)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("PlayerInput.Init", "()",
				SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050, ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050, MessageTarget.All, Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e();
			int i = 0;
			command.color = (Color)((UnityEngine.Color)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e();
			int i = 0;
			command.color = (Color)((UnityEngine.Color)args[i++]);
			ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(command);
		}

		void ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e command)
		{
			var target = Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e_CommandTarget;
			target.GotColor((UnityEngine.Color)(command.color));
		}
		void SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04();
			ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(command);
		}

		void ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04 command)
		{
			var target = Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04_CommandTarget;
			target.Hit();
		}
		void SendCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(MessageTarget target, object[] args)
		{
			var command = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050();
			ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(command);
		}

		void ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050 command)
		{
			var target = Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050_CommandTarget;
			target.Init();
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e castedCommand:
					ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_ColorRequester__char_46_GotColor_66a6aa74_9d10_4e8c_b171_36b364efe44e(castedCommand);
					break;
				case Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04 castedCommand:
					ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04(castedCommand);
					break;
				case Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050 castedCommand:
					ReceiveCommand_Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
