// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_58c1faddde8234d4692bc96b9f9ba54c_abf377b3_46fe_402f_b9db_7a484272bac7 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_58c1faddde8234d4692bc96b9f9ba54c_fad77f47_c076_4583_8fa0_ab214a41d542 : IntBinding
	{
		private global::Counter CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::Counter)UnityComponent;
		}
		public override string CoherenceComponentName => "Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter_6355730035801338076";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.counter);
			set => CastedUnityComponent.counter = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter_6355730035801338076)coherenceComponent).counter;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter_6355730035801338076)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.counter = Value;
			}
			else 
			{
				update.counter = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter_6355730035801338076();
		}
	}


	[Preserve]
	public class CoherenceSyncCounter_58c1faddde8234d4692bc96b9f9ba54c : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncCounter_58c1faddde8234d4692bc96b9f9ba54c>();

		// Cached targets for commands		
		private global::Counter Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["abf377b3-46fe-402f-b9db-7a484272bac7"] = new Binding_58c1faddde8234d4692bc96b9f9ba54c_abf377b3_46fe_402f_b9db_7a484272bac7(),
			["fad77f47-c076-4583-8fa0-ab214a41d542"] = new Binding_58c1faddde8234d4692bc96b9f9ba54c_fad77f47_c076_4583_8fa0_ab214a41d542(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncCounter_58c1faddde8234d4692bc96b9f9ba54c()
		{
			bakedCommandBindings.Add("47dae746-2173-47c0-b94a-e970baeab686", BakeCommandBinding_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686_CommandTarget = (global::Counter)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("Counter.NextNumber", "(Coherence.Toolkit.CoherenceSync)",
				SendCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686, ReceiveLocalCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686, MessageTarget.AuthorityOnly, Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncCounter_58c1faddde8234d4692bc96b9f9ba54c>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(MessageTarget target, object[] args)
		{
			var command = new Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686();
			int i = 0;
			command.requester = (SerializeEntityID)bridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(MessageTarget target, object[] args)
		{
			var command = new Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686();
			int i = 0;
			command.requester = (SerializeEntityID)bridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			ReceiveCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(command);
		}

		void ReceiveCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686 command)
		{
			var target = Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686_CommandTarget;
			target.NextNumber(bridge.EntityIdToCoherenceSync(command.requester));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686 castedCommand:
					ReceiveCommand_Counter_58c1faddde8234d4692bc96b9f9ba54c_Counter__char_46_NextNumber_47dae746_2173_47c0_b94a_e970baeab686(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncCounter_58c1faddde8234d4692bc96b9f9ba54c] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
