// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Coin__char_32_Spawner_8d9e8cf9c99d8da49bf515e68b4c8602_CoinSpawner__char_46_Init_677b316c_5815_448b_b793_cd86f1bf81c5 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalCoin__char_32_Spawner_8d9e8cf9c99d8da49bf515e68b4c8602_CoinSpawner__char_46_Init_677b316c_5815_448b_b793_cd86f1bf81c5;

		public static void Serialize(Coin__char_32_Spawner_8d9e8cf9c99d8da49bf515e68b4c8602_CoinSpawner__char_46_Init_677b316c_5815_448b_b793_cd86f1bf81c5 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Coin__char_32_Spawner_8d9e8cf9c99d8da49bf515e68b4c8602_CoinSpawner__char_46_Init_677b316c_5815_448b_b793_cd86f1bf81c5 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Coin__char_32_Spawner_8d9e8cf9c99d8da49bf515e68b4c8602_CoinSpawner__char_46_Init_677b316c_5815_448b_b793_cd86f1bf81c5
			(
			){};
		}
	}
}
