// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalCoin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44;

		public static void Serialize(Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Coin_f0b820c4d93e7a247ae2b37d3a1d9b32_Coin__char_46_RequestDestroy_113a2d09_0ad2_4bec_92ba_44995a582c44
			(
			){};
		}
	}
}
