// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Color__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7 : IEntityCommand
	{
		public SerializeEntityID requester;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalColor__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7;

		public Color__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7
		(
			SerializeEntityID datarequester
		)
		{
			requester = datarequester;
		}

		public static void Serialize(Color__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteEntity(commandData.requester);
		}

		public static Color__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7 Deserialize(IInProtocolBitStream bitStream)
		{
			var datarequester = bitStream.ReadEntity();

			return new Color__char_32_Giver_9d97557bee6ca2d44a4bc9037b5278ac_ColorGiver__char_46_RequestColor_a638e498_bd53_4b7b_9847_014c261072e7
			(
				datarequester
			){};
		}
	}
}
