// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0 : IEntityCommand
	{
		public Color color;
		public int coins;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalGame__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0;

		public Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0
		(
			Color datacolor,
			int datacoins
		)
		{
			color = datacolor;
			coins = datacoins;
		}

		public static void Serialize(Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0 commandData, IOutProtocolBitStream bitStream)
		{
			var converted_color = commandData.color.ToCoreColor();
			bitStream.WriteColor(converted_color, FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			bitStream.WriteIntegerRange(commandData.coins, 32, -2147483648);
		}

		public static Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0 Deserialize(IInProtocolBitStream bitStream)
		{
			var converted_color = bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			var datacolor = converted_color.ToUnityColor();
			var datacoins = bitStream.ReadIntegerRange(32, -2147483648);

			return new Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_ShowVictory_80d0961a_d2ce_4280_81b5_cd8d04601bc0
			(
				datacolor,
				datacoins
			){};
		}
	}
}
