// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_Victory_efc232bb_f749_4310_8c26_9b0d24cb3f1b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalGame__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_Victory_efc232bb_f749_4310_8c26_9b0d24cb3f1b;

		public static void Serialize(Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_Victory_efc232bb_f749_4310_8c26_9b0d24cb3f1b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_Victory_efc232bb_f749_4310_8c26_9b0d24cb3f1b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Game__char_32_Manager_e64e8343430fdef489c9172a49651adc_MainGameManager__char_46_Victory_efc232bb_f749_4310_8c26_9b0d24cb3f1b
			(
			){};
		}
	}
}
