// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04;

		public static void Serialize(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_Player__char_46_Hit_c2c9cd5c_69d7_4f17_9c6b_c032639a3e04
			(
			){};
		}
	}
}
