// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973 : ICoherenceComponentData
	{
		public Color color;

		public override string ToString()
		{
			return $"Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973(color: {color})";
		}

		public uint GetComponentType() => Definition.InternalPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973;

		public const int order = 0;

		public uint FieldsMask => 0b00000000000000000000000000000001;

		public int GetComponentOrder() => order;
		public bool IsSendOrdered() { return false; }

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				color = other.color;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static uint Serialize(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = (data.color.ToCoreColor());

				bitStream.WriteColor(fieldValue, FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			}
			mask >>= 1;

			return mask;
		}

		public static (Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973();
	
			if (bitStream.ReadMask())
			{
				val.color = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Player_acaa15b2fd77b2a4080fa3b9f1088f0e_UnityEngine__char_46_SpriteRenderer_2827779321465607973?;
	
		}
	}
}