// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050;

		public static void Serialize(Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_acaa15b2fd77b2a4080fa3b9f1088f0e_PlayerInput__char_46_Init_1037d901_6009_4a9c_a441_b730289e3050
			(
			){};
		}
	}
}
