// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Requester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc : IEntityCommand
	{
		public int number;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalRequester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc;

		public Requester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc
		(
			int datanumber
		)
		{
			number = datanumber;
		}

		public static void Serialize(Requester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteIntegerRange(commandData.number, 32, -2147483648);
		}

		public static Requester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc Deserialize(IInProtocolBitStream bitStream)
		{
			var datanumber = bitStream.ReadIntegerRange(32, -2147483648);

			return new Requester_9183cae5a9aea3f409ea10aa1e98898b_NumberRequester__char_46_GotNumber_d695b084_e661_4ae0_acc5_4b7a4ec195dc
			(
				datanumber
			){};
		}
	}
}
